### ISSUE TITLE
Disconnect method

### ISSUE THREAD

**Issue by rafaljanicki** [socialradar/memcache-plus#13]
Hello,

Firstly, let me thank you for developing the great plugin.

However, there is a one functionality that I miss in order to use the plugin on Lambda - disconnect(). Unfortunately, AWS Lambdas has to clear all the connections in order to finish execution - this includes memcached connections as well. Currently, the Lambdas are timing out due to connection working in a background.

Would you mind providing such function? Alternatively, I'll try to make a PR for that 

Best regards,
Rafal

**Comment by victorquinn** [comment]
Ahh, great point, will do!

**Comment by victorquinn** [comment]
Done! 

This is now live on npm as 0.2.7. 

I don't have any Lambda functions currently set up with Memcache so I couldn't test your specific use case, but this should properly disconnect which should make Lambda happy.

**Comment by rafaljanicki** [comment]
Works as expected, thank you!

**Comment by jnawk** [comment]
Is it possible to make the disconnect method clear the event loop?  At present, to use this with AWS Lambda, one has to either use the deprecated context.succeed() type methods, or set context.callbackWaitsForEmptyEventLoop to false - both are nice traps for novices.
