### ISSUE TITLE
No documentation.

### ISSUE THREAD

**Issue by thefabulousdev** [socialradar/memcache-plus#3]
Is there any documentation for the library?

**Comment by richswrighttj** [comment]
+1! Like what are the options etc?

**Comment by victorquinn** [comment]
Sorry, no docs at this time. It was an early oversight. I'm looking into what I can do now!

In the meantime, you can look to the [unit tests](https://github.com/socialradar/memcache-plus/blob/master/test/client.js) for some snippets/samples.

**Comment by victorquinn** [comment]
Happy to report that there is now documentation!

http://memcache-plus.com

**Comment by alexandrusavin** [comment]
The site is down. Would be nice if you could add it to Github wiki or README.md.

**Comment by victorquinn** [comment]
Sorry for the issues @alexandrusavin , it appears my domain provider changed my NS records. Site should be back up shortly.

**Comment by victorquinn** [comment]
And it's back up, apologies again!
