### ISSUE TITLE
Merge pull request?

### ISSUE THREAD

**Issue by luislobo** [socialradar/memcache-plus#7]
Hi,
I've pushed a pull request some time ago. I wonder if this project is being maintained, if not, I need to push this to NPM as a new project, that I would definitely try to avoid.
Thank you!

**Comment by victorquinn** [comment]
My apologies! It appears I was not getting notified of any issues or requests on this repo so they went unnoticed until you sent the one mentioning me!

I'll take a look and merge now if all looks well, my bad. I'll also update things so I get properly notified in the future :smile:

**Comment by victorquinn** [comment]
Looked great, merged! Sorry again!

**Comment by luislobo** [comment]
Thank you! No problem, sometimes this things happen. Will you be publishing it to NPM?

**Comment by victorquinn** [comment]
Already done, it's live on npm as 0.2.2
